# Generated by Django 4.2.1 on 2023-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('private_key', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
