# Generated by Django 4.2.1 on 2023-05-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekeys',
            name='user',
        ),
        migrations.AddField(
            model_name='privatekeys',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
