# Generated by Django 4.2.1 on 2023-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_addressdata_alter_privatekeys_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSeeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('seed', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PrivateKeys',
        ),
    ]
