# Generated by Django 4.2.1 on 2023-05-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_privateseeds_delete_privatekeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateseeds',
            name='seed_key',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
