# Generated by Django 4.2.1 on 2023-05-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_privateseeds_seed_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateseeds',
            name='seed_key',
        ),
    ]
