# Generated by Django 4.2.1 on 2023-05-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_privateseeds_seed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateseeds',
            name='seed_key',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
